language: php
php:
  - 5.5
  - 5.6
  - 7.0
script:
  - composer install
  - ./vendor/bin/phpunit tests
after_success:
  - php vendor/bin/coveralls -v
notifications:
  slack:
    secure: KDetZ5d4syHjXUoo2QuYXNPEBlZPFWhdlF3O/x1K1bPOMzLSQ+LqCkLMyWbg5BkOU9yqfvv1D4ny2lrx0bv9VtFaVqDjpyvMg0yzY18hSVmBb+BVmXUfBbVUwUO+6GvCOiN8Io2xrdp5zCa+mp4QXNy/NLOOY6bxndR5zSPTbhPFQg3nt05CHJWRpnczd4PtMBjFQMf9FLZk207cPKnAspN6vH1wdpu7oDkQdaogDfpzILdqYR+OInOA6MeeSNmfsT9L8eUfSflQ2k1nze6a9x+ngG/n3Yn6dGLy90R7tNFnpYdqY/vunuc6aRDncJGbBbxus+WInloAjWPhqMjYCC3xpqSZSWA79AITQJCsAMlH68upN205v5rriBrfegfy8mBP+favrY+ZoaXQHTaRtL/DlBIJnin6KK9Lmjhpq9JTEkUeisJo51EBqrsd8Db8Cte/d3GY7yR5m3HYieHQJXjyPhmmjKvEdS7MbF3wIGDn8n3BjoB/JOvh/zrjrPfMOtLZrEOujtjhPlMLldc0lVQ76cAno2a/q2OktEdl4nV/dAZByPH5MxDgUQDntxnf8w9d0uc7OG/AagUFAuo4MteWXv1x0gwc2Kh/HC8Ym4cwgF5A+8iGJKR9Mwt79ua/7IqH9tvm5dKx6vsJg+PtefLy909xamGCWVrquQKa3t0=
