<?php

namespace Crowdsdom\Tests\Integration\Labor\Models;

use Crowdsdom\Labor\Models\Task;
use Crowdsdom\Tests\Integration\TestCase;

class TaskTest extends ModelTest
{

    protected $model = Task::class;
    protected $data = 'task';

    public function setUp()
    {
        $this->skipCreate = true;
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCreate()
    {
        // not implemented
    }

    public function testFind()
    {
        // not implemented
    }

    public function testFindById()
    {
        // not implemented
    }

    public function testApprove()
    {
        try {
            $task = new Task($this->client);
            $task->approve("abc");
        } catch (\GuzzleHttp\Exception\ClientException $exception) {
            $this->assertEquals(404, $exception->getResponse()->getStatusCode());
        }
    }

    public function testReject()
    {
        try {
            $task = new Task($this->client);
            $task->reject("abc");
        } catch (\GuzzleHttp\Exception\ClientException $exception) {
            $this->assertEquals(404, $exception->getResponse()->getStatusCode());
        }
    }
}